# Generated by Django 3.1.4 on 2021-11-19 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('precaution', models.TextField(max_length=5000)),
                ('symptom', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='doc_DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Pincode', models.CharField(max_length=250)),
                ('Location', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('symptom1', models.CharField(max_length=30)),
                ('symptom2', models.CharField(blank=True, max_length=30)),
                ('symptom3', models.CharField(blank=True, max_length=30)),
                ('symptom4', models.CharField(blank=True, max_length=30)),
                ('symptom5', models.CharField(blank=True, max_length=30)),
                ('disease', models.CharField(max_length=30)),
                ('consultDoctor', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
